services:
  docker-remote-api:
    image: jarkt/docker-remote-api
    container_name: docker-remote-api
    ports:
      - "2375:2375" # Expose internal port 2375 to external port 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket
    logging:
      driver: "local"
